SEL-2.0: add one patch to fix livepatch compile issue
Compiler complains.

[  235s] ../kernel/livepatch/core.c: In function 'klp_enable_patch':
[  235s] ../kernel/livepatch/core.c:1548:6: error: void value not ignored as it ought to be
[  235s]  1548 |  ret = klp_init_patch_early(patch);
[  235s]       |      ^

And based on below mainline commits, one patch is added to resolve above
error.

50a0f3f55e38 livepatch: Fix missing unlock on error in klp_enable_patch()
5ef3dd20555e livepatch: Fix kobject refcount bug on klp_init_patch_early failure path

Reference: bsn#110

Signed-off-by: Guoqing Jiang <guoqing.jiang@suse.com>
Change-Id: I7b74a9452e5cb14622ae16d5ed58695cfba1352c