xfs: Fix 64-bit division on 32-bit in
From 18842e0a4f48564bbed541947abd8131fd0e9734 Mon Sep 17 00:00:00 2001
 xlog_state_switch_iclogs()
Git-commit: 18842e0a4f48564bbed541947abd8131fd0e9734
Patch-mainline: v5.14-rc1
References: bsn#12

On 32-bit (e.g. m68k):

    ERROR: modpost: "__udivdi3" [fs/xfs/xfs.ko] undefined!

Fix this by using a uint32_t intermediate, like before.

Reported-by: noreply@ellerman.id.au
Fixes: 7660a5b48fbef958 ("xfs: log stripe roundoff is a property of the log")
Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Reviewed-by: Dave Chinner <dchinner@redhat.com>
Reviewed-by: Darrick J. Wong <djwong@kernel.org>
Signed-off-by: Darrick J. Wong <djwong@kernel.org>
Signed-off-by: Guoqing Jiang <guoqing.jiang@suse.com>

Patch-name: patches.mainline/v5.14-rc1-xfs-Fix-64-bit-division-on-32-bit-in-xlog_state_swit.patch