packaging: only search 'Reference' one time
This file iterates patch header one by one, which causes problem
for patch which contains 'Reference' line already, eg, commit
860dafa90259 ("vt: Fix character height handling with VT_RESIZEX")
has the below line in header.

References:

Which causes the relevant patch can't be added to kernel-source
tree as follows

> git commit -s -e
ERROR: Problems encountered in `patches.stable/5840-vt-Fix-character-height-handling-with-VT_RESIZEX.patch'
** References: Value cannot be empty.
Please check README file for patch tag rules.
Aborting

So let's only check 'Reference' only once, thanks for Wei Qiang's
help.

Signed-off-by: Guoqing Jiang <guoqing.jiang@suse.com>
Change-Id: I39385372d12d8dfbb38e77106a2309e63c598dc8