SEL-2.0: fix a nic compiling error
Drop the patch v5.12-rc2-net-remove-ndo_udp_tunnel_-callbacks.patch to
fix this compiling error:

drivers/net/ethernet/netswift/txgbe/txgbe_main.c:7430:3:
error: ‘const struct net_device_ops’ has no member named ‘ndo_udp_tunnel_add’

 7430 |  .ndo_udp_tunnel_add     = txgbe_add_udp_tunnel_port,
      |   ^~~~~~~~~~~~~~~~~~
drivers/net/ethernet/netswift/txgbe/txgbe_main.c:7430:28:
error: initialization of ‘int (*)(struct net_device *, struct nlmsghdr *, u16)’ {aka ‘int (*)(struct net_device *, struct nlmsghdr *, short unsigned int)’} from incompatible pointer type ‘void (*)(struct net_device *, struct udp_tunnel_info *)’ [-Werror=incompatible-pointer-types]
 7430 |  .ndo_udp_tunnel_add     = txgbe_add_udp_tunnel_port,
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: d2b911d7 ("SEL-2.0: backport Intel NIC ixgbe patches from v5.16-rc6")
Signed-off-by: Geliang Tang <geliang.tang@suse.com>
Change-Id: I42c6cd05475bebb4694bcafac6482d79b62e3434