SEL-2.0: add two patches to resolve compile issue of damon
The timer patch is introduced to address below complain.

mm/damon/core.c: In function 'kdamond_usleep':
mm/damon/core.c:980:17: error: implicit declaration of function 'usleep_idle_range'; did you mean 'usleep_range'? [-Werror=implicit-function-declaration]
  980 |                 usleep_idle_range(usecs, usecs + 1);
      |                 ^~~~~~~~~~~~~~~~~
      |                 usleep_range
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:281: mm/damon/core.o] Error 1

Another one is used to address below err, and it was posted to list, so
need to be refreshed once it is accepted.

mm/damon/vaddr.c: In function ‘damon_va_evenly_split_region’:
./include/linux/damon.h:425:13: error: inlining failed in call to ‘always_inline’ ‘damon_insert_region’: function body not available
425 | inline void damon_insert_region(struct damon_region *r,
| ^~~~~~~~~~~~~~~~~~~
mm/damon/vaddr.c:86:3: note: called from here
86 | damon_insert_region(n, r, next, t);
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Reference: bsn#53

Signed-off-by: Guoqing Jiang <guoqing.jiang@suse.com>
Change-Id: I6146a26f5ff46b9e57c78a7296e2fcf69b7beaa3