SEL-2.0: add two acpi patches
The intel_pstate relies on acpi patch, otherwise compiler complains.

drivers/cpufreq/intel_pstate.c: In function ‘intel_pstate_cppc_nominal’:
drivers/cpufreq/intel_pstate.c:415:6: error: implicit declaration of function ‘cppc_get_nominal_perf’; did you mean ‘cppc_get_desired_perf’? [-Werror=implicit-function-declaration]
      415 |  if (cppc_get_nominal_perf(cpu, &nominal_perf))
          |      ^~~~~~~~~~~~~~~~~~~~~
          |      cppc_get_desired_perf

Also v5.15-rc1-ACPI-CPPC-Introduce-cppc_get_nominal_perf.patch depends
on v5.13-rc1-ACPI-CPPC-Add-emtpy-stubs-of-functions-for-CONFIG_AC.patch

Reference: bsn#46

Signed-off-by: Guoqing Jiang <guoqing.jiang@suse.com>
Change-Id: I49a399d1b39ea700f674b618ce39121acf22af79