mfd: mp2629: Select MFD_CORE to fix build error
Git-commit: 9b8bfdbc7e611a5b0ed45ef34c18ecfb42e66b25
References: bsn#19
Patch-mainline: v5.10.50

[ Upstream commit a933272041d852a1ef1c85f0c18b93e9999a41fa ]

MFD_MP2629 should select MFD_CORE to a prevent build error:

ERROR: modpost: "devm_mfd_add_devices" [drivers/mfd/mp2629.ko] undefined!

Fixes: 06081646450e ("mfd: mp2629: Add support for mps battery charger")
Signed-off-by: Randy Dunlap <rdunlap@infradead.org>
Signed-off-by: Lee Jones <lee.jones@linaro.org>
Signed-off-by: Sasha Levin <sashal@kernel.org>
Signed-off-by: Kai Liu <kai.liu@suse.com>

Patch-name: patches.stable/v5.10.50-0487-mfd-mp2629-Select-MFD_CORE-to-fix-build-error.patch