scsi: lpfc: Correct null ndlp reference on routine exit
From 9d8de441db261dbb4abb989674a62d1c13fe4f93 Mon Sep 17 00:00:00 2001
Git-commit: 9d8de441db261dbb4abb989674a62d1c13fe4f93
Patch-mainline: v5.11-rc1
References: bsn#61

smatch correctly called out a logic error with accessing a pointer after
checking it for null:

 drivers/scsi/lpfc/lpfc_els.c:2043 lpfc_cmpl_els_plogi()
 error: we previously assumed 'ndlp' could be null (see line 1942)

Adjust the exit point to avoid the trace printf ndlp reference. A trace
entry was already generated when the ndlp was checked for null.

Link: https://lore.kernel.org/r/20201130181226.16675-1-james.smart@broadcom.com
Fixes: 4430f7fd09ec ("scsi: lpfc: Rework locations of ndlp reference taking")
Reported-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: James Smart <james.smart@broadcom.com>
Signed-off-by: Martin K. Petersen <martin.petersen@oracle.com>
Signed-off-by: Guoqing Jiang <guoqing.jiang@suse.com>

Patch-name: patches.suse/v5.11-rc1-scsi-lpfc-Correct-null-ndlp-reference-on-routine-exi.patch