bus: ti-sysc: Fix variable set but not used warning for
Git-commit: e24fc8983025565e24f9438d3d514c280fecb0b7
 reinit_modules
References: bsn#19
Patch-mainline: v5.10.88

commit 1b1da99b845337362a3dafe0f7b49927ab4ae041 upstream.

Fix drivers/bus/ti-sysc.c:2494:13: error: variable 'error' set but not
used introduced by commit 9d881361206e ("bus: ti-sysc: Add quirk handling
for reinit on context lost").

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Tony Lindgren <tony@atomide.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Kai Liu <kai.liu@suse.com>

Patch-name: patches.stable/v5.10.88-0092-bus-ti-sysc-Fix-variable-set-but-not-used-warning-fo.patch