RDMA/hns: Add a check to ensure integer mtu is positive
From fe331da0f210c60342b042a03fe53f1b564b412b Mon Sep 17 00:00:00 2001
Git-commit: fe331da0f210c60342b042a03fe53f1b564b412b
Patch-mainline: v5.14-rc1
References: bsn#12
openEuler-commit: fb94f260b1085c892f15cfaf67c1c5ca823ccb43

GCC may reports an running time assert error when a value calculated from
ib_mtu_enum_to_int() is using as 'val' in FIELD_PREDP:

include/linux/compiler_types.h:328:38: error: call to
'__compiletime_assert_1524' declared with attribute error: FIELD_PREP:
value too large for the field

So a check is added about whether integer mtu from ib_mtu_enum_to_int() is
negative to avoid this warning.

Link: https://lore.kernel.org/r/1624262443-24528-3-git-send-email-liweihang@huawei.com
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Weihang Li <liweihang@huawei.com>
Signed-off-by: Jason Gunthorpe <jgg@nvidia.com>
Signed-off-by: Guoqing Jiang <guoqing.jiang@suse.com>

Patch-name: patches.mainline/v5.14-rc1-RDMA-hns-Add-a-check-to-ensure-integer-mtu-is-positi.patch