SEL-2.0: changes for vdpa subsystem
After enable CONFIG_VP_VDPA and CONFIG_VIRTIO_VDPA,
the below errors happened.

drivers/vdpa/virtio_pci/vp_vdpa.c:480:15: error: too many arguments to function 'vdpa_register_device'
  480 |         ret = vdpa_register_device(&vp_vdpa->vdpa, vp_vdpa->queues);
      |               ^~~~~~~~~~~~~~~~~~~~
./include/linux/vdpa.h:279:5: note: declared here
  279 | int vdpa_register_device(struct vdpa_device *vdev);
      |     ^~~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:287: drivers/vdpa/virtio_pci/vp_vdpa.o] Error 1

drivers/vhost/vdpa.c: In function 'vhost_vdpa_config_validate':
drivers/vhost/vdpa.c:195:35: error: 'const struct vdpa_config_ops' has no member named 'get_config_size'; did you mean 'get_config'?
  195 |         long size = vdpa->config->get_config_size(vdpa);
      |                                   ^~~~~~~~~~~~~~~
      |                                   get_config
make[2]: *** [scripts/Makefile.build:287: drivers/vhost/vdpa.o] Error 1
  CC [M]  drivers/virtio/virtio_vdpa.o
drivers/virtio/virtio_vdpa.c: In function 'virtio_vdpa_setup_vq':
drivers/virtio/virtio_vdpa.c:173:18: error: 'const struct vdpa_config_ops' has no member named 'get_vq_num_min'; did you mean 'get_vq_num_max'?
  173 |         if (ops->get_vq_num_min)
      |                  ^~~~~~~~~~~~~~
      |                  get_vq_num_max
drivers/virtio/virtio_vdpa.c:174:32: error: 'const struct vdpa_config_ops' has no member named 'get_vq_num_min'; did you mean 'get_vq_num_max'?
  174 |                 min_num = ops->get_vq_num_min(vdpa);
      |                                ^~~~~~~~~~~~~~
      |                                get_vq_num_max

We need to add two more vdpa patches and refresh another
vdpa patch to resolve them.

References: bsn#384

Signed-off-by: Guoqing Jiang <guoqing.jiang@suse.com>
Change-Id: I64643c91b4b9e3822f9abb1cdb9618b89411495e
(cherry picked from commit b3b68d914428549bc5e9eee9033404dee27b3f32)