SEL-2.0: fix arm64 compile error
After sync patches from 5.10.94, gcc complains about.

drivers/iommu/io-pgtable-arm.c: In function 'arm_lpae_do_split_blk':
drivers/iommu/io-pgtable-arm.c:742:54: error: passing argument 4 of 'arm_lpae_install_table' from incompatible pointer type [-Werror=incompatible-pointer-types]
  pte = arm_lpae_install_table(tablep, ptep, blk_pte, cfg);
                                                      ^~~
drivers/iommu/io-pgtable-arm.c:322:23: note: expected 'struct arm_lpae_io_pgtable *' but argument is of type 'struct io_pgtable_cfg *'
 static arm_lpae_iopte arm_lpae_install_table(arm_lpae_iopte *table,
                       ^~~~~~~~~~~~~~~~~~~~~~

Which is caused by

patches.stable/v5.10.94-0262-iommu-io-pgtable-arm-Fix-table-descriptor-paddr-form.patch

Fix the problem with change 'cfg' to 'data'.

Signed-off-by: Guoqing Jiang <guoqing.jiang@suse.com>
Change-Id: I6693da109b7717cf5af9dcb96da7abb8d910a037