trace/osnoise: Fix return value on
From 498627b4ac85780b9962ed9b5c5abbefd884ef8e Mon Sep 17 00:00:00 2001
 osnoise_init_hotplug_support
Git-commit: 498627b4ac85780b9962ed9b5c5abbefd884ef8e
Patch-mainline: v5.14-rc1
References: bsn#12

kernel test robot reported:

  >> kernel/trace/trace_osnoise.c:1584:2: error: void function
  'osnoise_init_hotplug_support' should not return a
  value [-Wreturn-type]
           return 0;

When !CONFIG_HOTPLUG_CPU.

Fix it problem by removing the return value.

Link: https://lkml.kernel.org/r/c7fc67f1a117cc88bab2e508c898634872795341.1624872608.git.bristot@redhat.com

Fixes: c8895e271f79 ("trace/osnoise: Support hotplug operations")
Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Daniel Bristot de Oliveira <bristot@redhat.com>
Signed-off-by: Steven Rostedt (VMware) <rostedt@goodmis.org>
Signed-off-by: Guoqing Jiang <guoqing.jiang@suse.com>

Patch-name: patches.mainline/v5.14-rc1-trace-osnoise-Fix-return-value-on-osnoise_init_hotpl.patch