SEL-2.0: sync patches from openEuler-22.03-LTS (2022-09-22)
1. Backport 4 mainline patches from 22.03-LTS.

2. Add 6 openEuler patches and 5 euleros patches.

3. Refresh one mainline patch.

4. Remove two openEuler patches which were added to fix kabi broken.
   However it caused compile error,

   error: 'struct iscsi_cls_conn' has no member named 'cleanup_work'

   after add

   v5.18-rc1-scsi-iscsi-Add-helper-functions-to-manage-iscsi_cls_conn.patch

   Given kabi is not a problem for now, let's remove them otherwise
   we will have trouble to add relevant mainline scsi patches.

Update kabi and configs, also fwlc per below.

> git rev-list --count v5.10..456781b0f3dfdfbe8935c6443211a5c8c622d8ce
18074

Signed-off-by: Guoqing Jiang <guoqing.jiang@suse.com>
Change-Id: I63cb0ac91c229f24eccb01638e33a2b59cf53b3b