bcache: fix a regression of code compiling failure in debug.c
From 33ec5dfe8f42aaf0163a16e2b450ab06f3a7f1f3 Mon Sep 17 00:00:00 2001
Message-Id: <33ec5dfe8f42aaf0163a16e2b450ab06f3a7f1f3.1638867260.git.geliang.tang@suse.com>
Git-commit: 33ec5dfe8f42aaf0163a16e2b450ab06f3a7f1f3
Patch-mainline: v5.13-rc1
References: bsn#32

The patch "bcache: remove PTR_CACHE" introduces a compiling failure in
debug.c with following error message,
  In file included from drivers/md/bcache/bcache.h:182:0,
                   from drivers/md/bcache/debug.c:9:
  drivers/md/bcache/debug.c: In function 'bch_btree_verify':
  drivers/md/bcache/debug.c:53:19: error: 'c' undeclared (first use in
  this function)
    bio_set_dev(bio, c->cache->bdev);
                     ^
This patch fixes the regression by replacing c->cache->bdev by b->c->
cache->bdev.

Signed-off-by: Coly Li <colyli@suse.de>
Cc: Christoph Hellwig <hch@lst.de>
Link: https://lore.kernel.org/r/20210411134316.80274-8-colyli@suse.de
Signed-off-by: Jens Axboe <axboe@kernel.dk>
Signed-off-by: Geliang Tang <geliang.tang@suse.com>

Patch-name: patches.suse/v5.13-rc1-bcache-fix-a-regression-of-code-compiling-failure-in.patch