SEL-2.0: fix perf build errors caused by libbpf upgrade
This patch fixes the following build errors caused by libbpf upgrade:

util/header.c: In function ‘write_bpf_prog_info’:
util/header.c:976:3: error: ‘bpf_program__bpil_addr_to_offs’ is deprecated: libbpf v0.6+: use a custom linear prog_info wrapper [-Werror=deprecated-declarations]
   bpf_program__bpil_addr_to_offs(node->info_linear);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from util/header.c:22:0:
/home/tgl/repos/3-kernel-source/tmp/linux-5.10-SEL-2.0.bk/tools/lib/bpf/libbpf.h:1168:1: note: declared here
 bpf_program__bpil_addr_to_offs(struct bpf_prog_info_linear *info_linear);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
util/header.c:982:3: error: ‘bpf_program__bpil_offs_to_addr’ is deprecated: libbpf v0.6+: use a custom linear prog_info wrapper [-Werror=deprecated-declarations]
   bpf_program__bpil_offs_to_addr(node->info_linear);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from util/header.c:22:0:
/home/tgl/repos/3-kernel-source/tmp/linux-5.10-SEL-2.0.bk/tools/lib/bpf/libbpf.h:1172:1: note: declared here
 bpf_program__bpil_offs_to_addr(struct bpf_prog_info_linear *info_linear);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
util/header.c: In function ‘process_bpf_prog_info’:
util/header.c:2928:3: error: ‘bpf_program__bpil_offs_to_addr’ is deprecated: libbpf v0.6+: use a custom linear prog_info wrapper [-Werror=deprecated-declarations]
   bpf_program__bpil_offs_to_addr(info_linear);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from util/header.c:22:0:
/home/tgl/repos/3-kernel-source/tmp/linux-5.10-SEL-2.0.bk/tools/lib/bpf/libbpf.h:1172:1: note: declared here
 bpf_program__bpil_offs_to_addr(struct bpf_prog_info_linear *info_linear);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC       util/fncache.o
  CC       util/machine.o
  CC       util/map.o

Closes: bsn#231
Signed-off-by: Geliang Tang <geliang.tang@suse.com>
Change-Id: I6531caef4cf70d89f22e6305216522e8db18dd13