parisc: parisc-agp requires SBA IOMMU driver
Git-commit: 597121792eb497e6442811767b310ed213f4d7ff
References: bsn#19
Patch-mainline: v5.10.30

commit 9054284e8846b0105aad43a4e7174ca29fffbc44 upstream.

Add a dependency to the SBA IOMMU driver to avoid:
ERROR: modpost: "sba_list" [drivers/char/agp/parisc-agp.ko] undefined!

Reported-by: kernel test robot <lkp@intel.com>
Cc: stable@vger.kernel.org
Signed-off-by: Helge Deller <deller@gmx.de>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>
Signed-off-by: Kai Liu <kai.liu@suse.com>

Patch-name: patches.stable/v5.10.30-0029-parisc-parisc-agp-requires-SBA-IOMMU-driver.patch