SEL-2.0: fix bpf kselftest build break
Fix the following bpf kselftest build break:

==============================================================================
In file included from tools/testing/selftests/bpf/prog_tests/sk_lookup.c:32:0:
tools/testing/selftests/bpf/prog_tests/sk_lookup.c: In function ‘run_sk_assign’:
tools/testing/selftests/bpf/prog_tests/sk_lookup.c:1092:15: error: ‘struct bpf_sk_lookup’ has no member named ‘cookie’
if (CHECK(ctx.cookie == 0, "ctx.cookie", "no socket selected\n"))
^
./test_progs.h:103:17: note: in definition of macro ‘_CHECK’
int __ret = !!(condition); \
^~~~~~~~~
tools/testing/selftests/bpf/prog_tests/sk_lookup.c:1092:6: note: in expansion of macro ‘CHECK’
if (CHECK(ctx.cookie == 0, "ctx.cookie", "no socket selected\n"))
^~~~~
tools/testing/selftests/bpf/prog_tests/sk_lookup.c:1095:11: error: ‘struct bpf_sk_lookup’ has no member named ‘cookie’
CHECK(ctx.cookie != server_cookie, "ctx.cookie",
^
./test_progs.h:103:17: note: in definition of macro ‘_CHECK’
int __ret = !!(condition); \
^~~~~~~~~
tools/testing/selftests/bpf/prog_tests/sk_lookup.c:1095:2: note: in expansion of macro ‘CHECK’
CHECK(ctx.cookie != server_cookie, "ctx.cookie",
^~~~~
tools/testing/selftests/bpf/prog_tests/sk_lookup.c:1096:49: error: ‘struct bpf_sk_lookup’ has no member named ‘cookie’
"selected sk %llu instead of %llu\n", ctx.cookie, server_cookie);
^
./test_progs.h:108:21: note: in definition of macro ‘_CHECK’
fprintf(stdout, ##format); \
^~~~~~
tools/testing/selftests/bpf/prog_tests/sk_lookup.c:1095:2: note: in expansion of macro ‘CHECK’
CHECK(ctx.cookie != server_cookie, "ctx.cookie",
^~~~~
TEST-OBJ [test_progs] select_reuseport.test.o
TEST-OBJ [test_progs] section_names.test.o
make: *** [Makefile:403: tools/testing/selftests/bpf/sk_lookup.test.o] Error 1
make: *** Waiting for unfinished jobs....
==============================================================================

It's because only one patch "selftests: bpf: Convert sk_lookup ctx access
tests to PROG_TEST_RUN" of the 'PROG_TEST_RUN support for sk_lookup
programs' series was backported:

b0d3df486fcf Merge branch 'PROG_TEST_RUN support for sk_lookup programs'
b4f894633fa1 selftests: bpf: Don't run sk_lookup in verifier tests
abab306ff04b selftests: bpf: Check that PROG_TEST_RUN repeats as requested
509b2937bce9 selftests: bpf: Convert sk_lookup ctx access tests to PROG_TEST_RUN
7c32e8f8bc33 bpf: Add PROG_TEST_RUN support for sk_lookup programs
607b9cc92bd7 bpf: Consolidate shared test timing code

This patch added the other four missing patches in this series.

Closes: bsn#142
Signed-off-by: Geliang Tang <geliang.tang@suse.com>
Change-Id: I4c7c89f2011f5e9226883242787080d1076da731