resctrlfs: fix up RESCTRL dependency
From e3e6ca3fe091af5883a916ad4b1c896b7ffc8337 Mon Sep 17 00:00:00 2001
Patch-mainline: Not yet, from openEuler
References: bsn#22
openEuler-commit: e3e6ca3fe091af5883a916ad4b1c896b7ffc8337

hulk inclusion
category: bugfix
feature: ARM MPAM support
bugzilla: 48265
CVE: NA

--------------------------------

On x86 platform,
make allmodconfig && make -j64

  CALL    scripts/checksyscalls.sh
  DESCEND  objtool
  CHK     include/generated/compile.h
  CC      fs/resctrlfs.o
fs/resctrlfs.c:36:25: fatal error: asm/resctrl.h: No such file or
directory
 #include <asm/resctrl.h>
                         ^
compilation terminated.
make[1]: *** [fs/resctrlfs.o] Error 1
make: *** [fs] Error 2

Make RESCTRL do not depend on INTEL_RDT.

Signed-off-by: Xie XiuQi <xiexiuqi@huawei.com>
Reviewed-by: Yang Yingliang <yangyingliang@huawei.com>
Signed-off-by: Yang Yingliang <yangyingliang@huawei.com>
Signed-off-by: Wang ShaoBo <bobo.shaobowang@huawei.com>
Reviewed-by: Cheng Jian <cj.chengjian@huawei.com>
Signed-off-by: Zheng Zengkai <zhengzengkai@huawei.com>
Signed-off-by: Guoqing Jiang <guoqing.jiang@suse.com>

Patch-name: patches.openEuler/3118-resctrlfs-fix-up-RESCTRL-dependency.patch